### ISSUE TITLE
audio

### ISSUE THREAD

**Issue by ghost** [Reyansh-Khobragade/bad-apple-nodejs#1]
sar add audio 2

**Comment by ItzSudhan** [comment]
> amogus i will try doin em
didnt worked ;_;

**Comment by ghost** [comment]
sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio sar add audio

**Comment by Reyansh-Khobragade** [comment]
Its working but a lil buggy, will push to main when I am done fixing the bugs *(hope i don't stay lazy)*
